### ISSUE TITLE
ModuleNotFoundError: No module named '_signDNE_cli'

### ISSUE THREAD

**Issue by ddevriespaleo** [frisbro303/signDNE_python#8]
Dear frisbro303,

I look forward to using this package and calculate sign-oriented ariaDNE in python rather than MatLab. 

I receive the following error when trying to run the first example command [signDNE path/to/mesh.ply -v] error: 

"Traceback (most recent call last):
  File "/usr/local/bin/signDNE", line 5, in <module>
    from _signDNE_cli import main
ModuleNotFoundError: No module named '_signDNE_cli'"

Is there a way to fix this? Thank you!

**Comment by ddevriespaleo** [comment]
Dear Felix,

Thank you for your quick reply! I installed it with that line (although had to use "pip3" instead of "pip"). I'm working with an older Macbook (10.15.7). It may be an issue with my outdated OS. 

Thank you for your help,
Dorien

**Comment by ddevriespaleo** [comment]
I've managed to run the MATLAB code, so I will close this python issue for now (it is probably linked to my laptop, outdated packages, and multiple python versions!).

**Comment by frisbro303** [comment]
I'm sorry that the python version didn't end up working on your machine, but I'm glad to hear that you got the MATLAB version running instead. If you are still interested in the python version you can also clone the repository and run the _signDNE_cli directly. 
Best regards, Felix
